# default configuration and possible options:
#  - https://github.com/bbatsov/rubocop/blob/master/config/default.yml
#  - https://github.com/bbatsov/rubocop/blob/master/config/disabled.yml
#  - https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

# https://github.com/bbatsov/ruby-style-guide#80-character-limits
Metrics/LineLength:
  Max: 100

# https://github.com/bbatsov/ruby-style-guide#short-methods
Metrics/MethodLength:
  Max: 28

# http://c2.com/cgi/wiki?AbcMetric
Metrics/AbcSize:
  Max: 45

Style/Documentation:
  Enabled: false

# https://github.com/bbatsov/ruby-style-guide#until-for-negatives
Style/NegatedWhile:
  Enabled: false

# https://github.com/bbatsov/ruby-style-guide#no-parens-if
Style/ParenthesesAroundCondition:
  Exclude:
    - lib/hiogawa_playground/mst.rb

# https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals
Style/Next:
  Exclude:
    - lib/hiogawa_playground/mst.rb

# https://github.com/bbatsov/ruby-style-guide#no-non-nil-checks
Style/NonNilCheck:
  Enabled: false

# https://github.com/bbatsov/ruby-style-guide#until-for-negatives
Style/GuardClause:
  Enabled: false
